
pipeline {
    agent any

    stages {
        stage('Check Connection') {
                
            steps {
                script{

                        sshagent(['79a4420b-3683-4745-a8a1-9e27b796f7b3']) {
                            sh '''
                            ssh shihab@192.168.1.12 "echo "server running....""
                            '''
               
                        }
              
                    }
                   
                }

            post {
                success {
                       notifyDiscord("Connection success!")
                }
                failure {
                     notifyDiscord("Connection failed!")
                }
            }
            
        }

        stage('update code') {
            steps {
                script{

                       sshagent(['79a4420b-3683-4745-a8a1-9e27b796f7b3']) {
                            sh '''
                            ssh shihab@192.168.1.12 "
                            cd /home/shihab/Documents/jenkins-workspace/brain-23 &&
                            sudo git reset .  && 
                            sudo git clean -df &&
                            sudo git stash &&
                            sudo git pull
                            
                            "
                            '''
               
                        }
              
                    }
                   
                }

             post {
                success {
                       notifyDiscord("update code  success!")
                }
                failure {
                     notifyDiscord("update code failed!")
                }
            }
       
        }
 
        stage('build code') {
            steps {
                script{

                       sshagent(['79a4420b-3683-4745-a8a1-9e27b796f7b3']) {
                            sh '''
                            ssh shihab@192.168.1.12 "
                                   cd /home/shihab/Documents/jenkins-workspace/brain-23/task1/app2 &&
                                   sudo ./build-test.bash
                            
                            "
                            '''
               
                        }
              
                    }
                   
                }
            
             post {
                success {
                       notifyDiscord("build success!")
                }
                failure {
                     notifyDiscord("build failed!")
                }
            }
       
        }

         stage('deploy code') {
            steps {
                script{

                       sshagent(['79a4420b-3683-4745-a8a1-9e27b796f7b3']) {
                            sh '''
                            ssh shihab@192.168.1.12 "
                                    cd /home/shihab/Documents/jenkins-workspace/brain-23/task1/app2 &&
                                    sudo kubectl apply -f deploy 
                            
                            "
                            '''
               
                        }
              
                    }
                   
                }

              post {
             
                success {
                       notifyDiscord("deploy success!")
                }
                failure {
                     notifyDiscord("deploy failed!")
                }
            }
        }

        
        
    }

}
def notifyDiscord(message) {
    def discordWebhookUrl = 'https://discord.com/api/webhooks/1145653952562597918/b9wR-EbUYiBOOsn3jHGxq1Cg45sGiz45yfo_ASMtAXZzMmhpyvvzQCEl7EL-OBrwUXgS'
    sh "curl -X POST -H 'Content-Type: application/json' -d '{\"content\":\"${message}\"}' ${discordWebhookUrl}"
}
    